name: CI

on:
  push:
  pull_request:
#  schedule:
#    - cron: "0 23 * * *" # everyday at 11pm


jobs:
  industrial_ci:
    timeout-minutes: 60
    env:
      ADDITIONAL_DEBS: 'apt-utils curl dialog git-core openssh-client openssh-server wget'
      AFTER_SCRIPT: 'rosenv bash .travis.xacro_test.sh'
      AFTER_INIT: mkdir -p ~/.ssh && touch ~/.ssh/known_hosts && ssh-keyscan github.com >> ~/.ssh/known_hosts && curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash && apt-get install git-lfs -y && cd $HOME && git lfs install && cd -
      CATKIN_LINT: pedantic
      CATKIN_LINT_ARGS: '--ignore description_boilerplate'
      CMAKE_ARGS: -DCMAKE_BUILD_TYPE=Release
      NOT_TEST_DOWNSTREAM: true
      PYLINT_ARGS: "--output-format=parseable --errors-only"
      PYLINT2_CHECK: true  # pylint2 for kinetic, pylint3 for noetic
      PYLINT3_CHECK: false
      ROS_REPO: main
      VERBOSE_OUTPUT: false
      VERBOSE_TESTS: false
    strategy:
      matrix:
        env:
          - { ROS_DISTRO: kinetic,
              UPSTREAM_WORKSPACE: '.ci.rosinstall.kinetic'
            }
          - { ROS_DISTRO: noetic
            }
    name: ${{matrix.env.ROS_DISTRO}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Checkout LFS objects
        run: git lfs checkout
      - uses: 'fmessmer/industrial_ci@master_pylint'
        env: ${{matrix.env}}
